
////mine
export const GET_LEGISLATION_FILE = 'LEGISLATION_FILE/GET_LEGISLATION_FILE'
export const PUT_LEGISLATION_FILE = 'LEGISLATION_FILE/PUT_LEGISLATION_FILE'
export const DELETE_LEGISLATION_FILE = 'LEGISLATION_FILE/DELETE_LEGISLATION_FILE'
export const SET_LEGISLATION_FILE = 'LEGISLATION_FILE/SET_LEGISLATION_FILE'
export const SET_LEGISLATION_FILES = 'LEGISLATION_FILE/SET_LEGISLATION_FILES'
export const STORE_LEGISLATION_FILE = 'LEGISLATION_FILE/STORE_LEGISLATION_FILE'
export const GET_LEGISLATION_FILES = 'LEGISLATION_FILE/GET_LEGISLATION_FILES'