
////mine
export const GET_LEGISLATION = 'LEGISLATION/GET_LEGISLATION'
export const PUT_LEGISLATION = 'LEGISLATION/PUT_LEGISLATIONS'
export const DELETE_LEGISLATION = 'LEGISLATION/DELETE_LEGISLATIONS'
export const SET_LEGISLATION = 'LEGISLATION/SET_LEGISLATION'
export const SET_PARENT_LEGISLATION = 'LEGISLATION/SET_PARENT_LEGISLATION'
export const SET_LEGISLATIONS = 'LEGISLATION/SET_LEGISLATIONS'
export const STORE_LEGISLATION = 'LEGISLATION/STORE_LEGISLATION'
export const STORE_LEGISLATION_CATEGORY = 'LEGISLATION/STORE_LEGISLATION_CATEGORY'
export const GET_LEGISLATIONS = 'LEGISLATION/GET_LEGISLATIONS'