export const GET_PASSWORDS = 'PASSWORD/GET_PASSWORDS'
export const SET_PASSWORDS = 'PASSWORD/SET_PASSWORDS'
export const ADD_PASSWORD  = 'PASSWORD/ADD_PASSWORD'
export const POST_PASSWORD = 'PASSWORD/POST_PASSWORD'