export const GET_QUESTION  = 'QUESTIONS/GET_QUESTION'
export const SET_QUESTION  = 'QUESTIONS/SET_QUESTION'
export const GET_QUESTIONS = 'QUESTIONS/GET_QUESTIONS'
export const SET_QUESTIONS = 'QUESTIONS/SET_QUESTIONS'