
////mine
export const GET_RECEPTION = 'RECEPTION/GET_RECEPTION'
export const PUT_RECEPTION = 'RECEPTION/PUT_RECEPTION'
export const DELETE_RECEPTION = 'RECEPTION/DELETE_RECEPTION'
export const SET_RECEPTION = 'RECEPTION/SET_RECEPTION'
export const SET_RECEPTIONS = 'RECEPTION/SET_RECEPTIONS'
export const STORE_RECEPTION = 'RECEPTION/STORE_RECEPTION'
export const GET_RECEPTIONS = 'RECEPTION/GET_RECEPTIONS'